Add docker module to report on docker assets
enkore/i3pystatus pull request #838
Opened 2022-03-12 20:19 UTC by drwahl

Signed-off-by: David Wahlstrom <david.wahlstrom@dreamhost.com>

2022-03-22 21:00 UTC, terminalmage requested changes

2022-03-22 21:00 UTC, terminalmage commented on i3pystatus/docker.py
> +    """
Can you add some documentation here about the available formatters?

2025-06-17 01:50 UTC, chestm007 commented
this errors out when no containers are running as containers['running'] isnt populated. ive hacked around it be setting that to 0 for now before the output is calculated, but it feels dirty

2025-06-23 15:32 UTC, chestm007 commented
merging, ill push a patch to clear up the issue shortly after

2025-06-23 15:32 UTC, merged